from __future__ import annotations

import json

from sirius.agents.base import Agent, AgentContext
from sirius.llm.base import ToolSpec
from sirius.study.service import StudyService


class StudyAgent(Agent):
    """Owns the learning system: logs study sessions and exposes progress so the
    LLM can act as an increasingly informed tutor. Quizzes, flashcards, and study
    plans are generated by the model itself, guided by this history."""

    name = "study"

    def __init__(self, study: StudyService) -> None:
        self._study = study

    def system_hint(self) -> str:
        return (
            "Study: when the user studies or practices a topic, log it with log_study_session. "
            "Check get_study_progress before tutoring so you can build on prior sessions, "
            "revisit weak areas, and increase difficulty over time. You can generate quizzes, "
            "flashcards, explanations, and study plans directly."
        )

    def tools(self) -> list[ToolSpec]:
        return [
            ToolSpec(
                "log_study_session",
                "Record that the user studied a topic (e.g. python, sql, mandarin).",
                {
                    "type": "object",
                    "properties": {
                        "topic": {"type": "string"},
                        "minutes": {"type": "integer"},
                        "notes": {
                            "type": "string",
                            "description": "What was covered; mistakes to review later.",
                        },
                    },
                    "required": ["topic", "minutes"],
                },
            ),
            ToolSpec(
                "get_study_progress",
                "Per-topic study totals and recent sessions, most-studied first.",
                {"type": "object", "properties": {}},
            ),
        ]

    def execute(self, tool_name: str, args: dict, ctx: AgentContext) -> str:
        if tool_name == "log_study_session":
            self._study.log_session(
                ctx.user_id, args["topic"], args["minutes"], args.get("notes", "")
            )
            return "Study session logged."
        if tool_name == "get_study_progress":
            progress = self._study.progress(ctx.user_id)
            recent = [
                {"topic": s.topic, "minutes": s.minutes, "notes": s.notes[:200]}
                for s in self._study.recent(ctx.user_id, limit=5)
            ]
            return json.dumps({"totals": progress, "recent": recent})
        raise ValueError(f"Unknown tool: {tool_name}")
